### PR TITLE
Fix content type (2)

### PR DESCRIPTION
**Pull request by joker314**
From #18 

> I think I have the wrong version of one of the testing tools because the tests could not run locally. Sorry for all the commits!
>
> ## Changes
> - The Content-Type is set to `text/plain`
>
> ## Testing
> - Manually navigated
> - Automatic testing

### CODE REVIEW

**Comment by joker314** [comment]
The pull request is identical to the previous one

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
btw what issues were you experiencing locally with running the tests?

**Comment by joker314** [comment]
For each test file:

```
 FAIL  __tests__\validatePolicy.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)
```
I guess I need to update jsdom.

For linting:

```
standard: Use JavaScript Standard Style (https://standardjs.com)
  C:\Users\Max\documents\express-security-txt\__tests__\formatPolicy.test.js:0:0: Parsing error: Cannot read property 'ecmaFeatures' of undefined
  C:\Users\Max\documents\express-security-txt\__tests__\middleware.test.js:0:0: Parsing error: Cannot read property 'ecmaFeatures' of undefined
  C:\Users\Max\documents\express-security-txt\__tests__\validatePolicy.test.js:0:0: Parsing error: Cannot read property 'ecmaFeatures' of undefined
  C:\Users\Max\documents\express-security-txt\example.js:0:0: Parsing error: Cannot read property 'ecmaFeatures' of undefined
  C:\Users\Max\documents\express-security-txt\index.js:0:0: Parsing error: Cannot read property 'ecmaFeatures' of undefined
```

**Comment by joker314** [comment]
Oh. I ran `npm install` rather than `yarn install`. Whoops!

**Comment by lirantal** [comment]
That makes sense :-)

**Pull request merged**
