### PR TITLE
Add "Expires" directive from draft v10

### PR DESCRIPTION
**Pull request by bkimminich**
(see https://tools.ietf.org/html/draft-foudil-securitytxt-10#section-3.5.5)

### CODE REVIEW

**Comment by lirantal** [comment]
This however doesn't specifically add anything to the schema of fields, right?
Could you take a look again and also add the relevant test cases for it?

**Review by joker314 — CHANGES_REQUESTED** [review]
Hi, thanks for the PR!

I think the schema changes are essential, otherwise joi will reject an object that contains an `expires` key with an error. I'm happy to file a PR to do this if you're not sure how to do it or don't have time to make the change.

**Comment by bkimminich** [comment]
I've added the field to the schema but didn't write any tests as the test suite is broken when running on my Win10 machine throwing errors accessing `localStorage`. Also I didn't make the field mandatory although the latest spec says it is, because I didn't want this to become a breaking chance PR.

**Comment by bkimminich** [comment]
Tests seem to pass on Travis-CI, linter now does too. Only problem is a complaint on the RegEx I used for date validation. Unfortunately `security.txt` went for the very verbose RFC5322 date format. There might be better RegExes out there to check for it not triggering your security checks, or maybe you want to drop the strict format check altogether?

**Review by joker314 — COMMENTED** [review]
Thank you very much!

It looks like the security error is a slight false positive if it's looking for catastrophic backtracking, feel free to add a comment to instruct eslint to ignore it, like we do here: https://github.com/lirantal/express-security-txt/blob/98710b8f51d8696cfc301a0c6bf562b5f305a762/index.js#L83

Could you make the expires a required key in joi (like Contact)?

Don't worry about tests (I think I had some issues setting it up on Windows too), I can write some since the testing system works for me locally

**Comment by joker314** [comment]
Looks good, I'll add some tests (and fix the existing ones, since they're now failing for not having the required Expires field and then we'll merge

**Comment by joker314** [comment]
Sorry for the delay - I've just pushed a commit which will make all the existing tests pass again. Later today, I'll push another commit which will add some extra tests to make sure the new validation works correctly

**Comment by joker314** [comment]
The regular expression is a bit complicated (unnecessary capturing groups, using `[0-9]` instead of `\d`), and from my reading contains some mistakes (`[+|-]` should be `[+-]`, some of the quantifiers seem to be in the wrong places, etc.). Additionally, it is unable to validate certain aspects -- such as whether the day of the week actually corresponds to the date.

I suggest that instead of using strings, which have a lot of problems, we require that people provide `Date` objects and then we do the conversion into a string. This guarantees that our output will always be valid. I'm sorry that you wrote the RegEx and now I don't want to use it, but I think it's the best way forward.

What are your thoughts on this @bkimminich @lirantal

**Comment by bkimminich** [comment]
Sounds totally reasonable to take a Date object. I only copy-pasted that RegEx from somewhere, so no hard feelings about it going unused... 😁

**Comment by lirantal** [comment]
Great work on this folks, thank you both for keeping up with the PR 🙏🏼

**Comment by joker314** [comment]
The GitHub version of the draft has been changed to use a different time format, ISO 8601, which is something that JavaScript natively supports. It might be worth starting the PR again from scratch? Hopefully it will be more straightforward to validate and generate now.

**Comment by lirantal** [comment]
@bkimminich what do you think?

**Comment by bkimminich** [comment]
Feel free to scrap this PR and implement it from scratch! 👍

**Comment by joker314** [comment]
Awesome, that's what I'll do. Sorry once again

**Pull request closed without merging**
