### PR TITLE
Fix content type

### PR DESCRIPTION
**Pull request by joker314**
I think I have the wrong version of one of the testing tools because the tests could not run locally. Sorry for all the commits!

## Changes
- The Content-Type is set to `text/plain`

## Testing
- Manually navigated
- Automatic testing

### CODE REVIEW

**Review by lirantal — APPROVED** [review]
LGTM

**Comment by joker314** [comment]
So I messed up the semantic versioning and decided to force push to fix it.

**Comment by joker314** [comment]
Maybe that was a bad idea. The change is no longer in master, but I can't re-merge this pull request. I'm really sorry about this. I guess I should file another PR and try again?

(EDIT: or I could attempt to merge from the command line. Would that still get all the bots which do the releases to update?)

Update: I've managed to merge it locally. Should I push it out to master?

**Comment by lirantal** [comment]
No worries, it's ok we all make mistakes.

It will be great if you can just open a new PR with the proposed changes. Let me know if you need any git related help with that.

**Pull request merged**
